=== kmike11/LWUIJ2WebXML/XMLTaskLWUIJ2/XMLSchemaLWUIJ2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="root">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Versenyzok">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Versenyzo" maxOccurs="1000">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="VNev" type="xs:string" />
                                        <xs:element name="Sz_adatok">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="Szul_ido" type="szulido" />
                                                    <xs:element name="Szul_hely" type="xs:string" />
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="VAzon" type="xs:string" />
                                    <xs:attribute name="Szektorazon" type="xs:string" />
                                    <xs:attribute name="Dazon" type="xs:string" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Doksik">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Doksi" maxOccurs="1000">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Igazolvany" type="xs:string" />
                                    </xs:sequence>
                                    <xs:attribute name="Vazon" type="xs:string" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Verseny_Birok">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Verseny_Biro" minOccurs="1" maxOccurs="1000">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="VNev" type="xs:string" />
                                        <xs:element name="KNev" type="xs:string" />
                                        <xs:element name="Sz_adatok">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="Szul_ido" type="szulido" />
                                                    <xs:element name="Szul_hely" type="xs:string" />
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="BAzon" type="xs:string"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Kifogott_Halak">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Kifogott_hal" minOccurs="1" maxOccurs="1000">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="THal" type="xs:string"/>
                                        <xs:element name="Kg" type="xs:string"/>
                                        <xs:element name="ido" type="xs:string"/>
                                    </xs:sequence>
                                    <xs:attribute name="Hazon" type="xs:string"/>
                                    <xs:attribute name="Halindex" type="xs:string"/>
                                    <xs:attribute name="VerAzon" type="xs:string"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Ellenorzesek">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Ellenorzes" minOccurs="1" maxOccurs="1000">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Mikor" type="idoType"/>
                                    </xs:sequence>
                                    <xs:attribute name="VersenyzoId" type="xs:string"/>
                                    <xs:attribute name="VBiroId" type="xs:string"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Dijak">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Dij" minOccurs="1" maxOccurs="1000">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="DNev" type="xs:string"/>
                                        <xs:element name="Erteke" type="xs:string"/>
                                        <xs:element name="At_adasi_idopont" type="idoType"/>
                                    </xs:sequence>
                                    <xs:attribute name="Dazon" type="xs:string"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Helyszinek">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Helyszin" minOccurs="1" maxOccurs="1000">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Helyszin_tipusa" type="xs:string"/>
                                        <xs:element name="Meret" type="xs:positiveInteger"/>
                                        <xs:element name="Szektor" type="xs:string"/>
                                    </xs:sequence>
                                    <xs:attribute name="SzektorAzon" type="xs:string"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Hal_Tipusok">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Hal_Tipus" minOccurs="1" maxOccurs="1000">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Ragadozo" type="xs:string"/>
                                        <xs:element name="Tipusa" type="xs:string"/>
                                        <xs:element name="Oshonos" type="xs:string"/>
                                    </xs:sequence>
                                    <xs:attribute name="index" type="xs:string"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
        <xs:key name="dij_Key">
            <xs:selector xpath="Dij"/>
            <xs:field xpath="@Dazon"/>
        </xs:key>
        <xs:key name="Versenyzo_Key">
            <xs:selector xpath="Versenyzo"/>
            <xs:field xpath="@VAzon"/>
        </xs:key>
        <xs:key name="kifogottHal_Key">
            <xs:selector xpath="Kifogott_hal"/>
            <xs:field xpath="@Hazon"/>
        </xs:key>
        <xs:key name="VersenyBir_Key">
            <xs:selector xpath="Verseny_Biro"/>
            <xs:field xpath="@Bazon"/>
        </xs:key>
        <xs:key name="Hal_Tipus_key">
            <xs:selector xpath="Hal_Tipus"/>
            <xs:field xpath="@index"/>
        </xs:key>
        <xs:key name="helyszin_key">
            <xs:selector xpath="Helyszin"/>
            <xs:field xpath="@SzektorAzon"/>
        </xs:key>
        <xs:keyref name="Fkey_dij_Versenyzo" refer="dij_Key">
            <xs:selector xpath="Versenyzo"/>
            <xs:field xpath="@Dazon"/>
        </xs:keyref>
        <xs:keyref name="Fkey_H-V_VersenyBiro" refer="VersenyBir_Key">
            <xs:selector xpath="Ellenorzes"/>
            <xs:field xpath="@VBiroId"/>
        </xs:keyref>
        <xs:keyref name="Fkey_H-V_Versenyzo" refer="Versenyzo_Key">
            <xs:selector xpath="Ellenorzes"/>
            <xs:field xpath="@VersenyzoId"/>
        </xs:keyref>
        <xs:keyref name="Fkey_Hal_Tipus_Kifogott_hal" refer="Hal_Tipus_key">
            <xs:selector xpath="Kifogott_hal"/>
            <xs:field xpath="@Halindex"/>
        </xs:keyref>
        <xs:keyref name="Fkey_Kifogott_hal_Versenyzo" refer="Versenyzo_Key">
            <xs:selector xpath="Kifogott_hal"/>
            <xs:field xpath="@VerAzon"/>
        </xs:keyref>
        <xs:keyref name="Fkey_Helyszin_Versenyzo" refer="helyszin_key">
            <xs:selector xpath="Versenyzo"/>
            <xs:field xpath="@Szektorazon"/>
        </xs:keyref>
        <xs:keyref name="Fkey_Doksi_Versenyzo" refer="Versenyzo_Key">
            <xs:selector xpath="Doksi"/>
            <xs:field xpath="@Vazon"/>
        </xs:keyref>
    </xs:element>
    <xs:simpleType name="idoType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{1}[0-9]{1}:[0-9]{1}[0-9]{1}" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="szulido">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{4}[.]\d{2}[.]\d{2}" />
            <xs:length value="10"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== kmike11/LWUIJ2WebXML/XMLTaskLWUIJ2/DOMParseLWUIJ2/XMLLWUIJ2out.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="DOMParseLWUIJ2/XMLSchemaLWUIJ2.xsd">
    <Versenyzok>
        <Versenyzo Dazon="1" Szektorazon="1" VAzon="1">
            <VNev>Bence</VNev>
            <Sz_adatok>
                <Szul_ido>1997.01.06</Szul_ido>
                <Szul_hely>Gyula</Szul_hely>
            </Sz_adatok>
        </Versenyzo>
        <Versenyzo Dazon="2" Szektorazon="2" VAzon="2">
            <VNev>Akos</VNev>
            <Sz_adatok>
                <Szul_ido>2000.10.15</Szul_ido>
                <Szul_hely>Miskolc</Szul_hely>
            </Sz_adatok>
        </Versenyzo>
        <Versenyzo Dazon="3" Szektorazon="3" VAzon="3">
            <VNev>Alex</VNev>
            <Sz_adatok>
                <Szul_ido>1999.03.20</Szul_ido>
                <Szul_hely>Budapest</Szul_hely>
            </Sz_adatok>
        </Versenyzo>
    </Versenyzok>
    <Doksik>
        <Doksi Vazon="1">
            <Igazolvany>Taj_Kartya</Igazolvany>
        </Doksi>
        <Doksi Vazon="2">
            <Igazolvany>Vezetoi_Engedely</Igazolvany>
        </Doksi>
        <Doksi Vazon="3">
            <Igazolvany>Szig_szam</Igazolvany>
        </Doksi>
        <Doksi Vazon="4">
            <Igazolvany>Lakcim_kartya</Igazolvany>
        </Doksi>
    </Doksik>
    <Verseny_Birok>
        <Verseny_Biro BAzon="1">
            <VNev>Kiss</VNev>
            <KNev>Joe</KNev>
            <Sz_adatok>
                <Szul_ido>1980.06.20</Szul_ido>
                <Szul_hely>Budapest</Szul_hely>
            </Sz_adatok>
        </Verseny_Biro>
        <Verseny_Biro BAzon="2">
            <VNev>Nagy</VNev>
            <KNev>Ferenc</KNev>
            <Sz_adatok>
                <Szul_ido>1985.12.03</Szul_ido>
                <Szul_hely>Sopron</Szul_hely>
            </Sz_adatok>
        </Verseny_Biro>
        <Verseny_Biro BAzon="3">
            <VNev>Kovacs</VNev>
            <KNev>Janos</KNev>
            <Sz_adatok>
                <Szul_ido>1975.02.10</Szul_ido>
                <Szul_hely>Gyor</Szul_hely>
            </Sz_adatok>
        </Verseny_Biro>
    </Verseny_Birok>
    <Kifogott_Halak>
        <Kifogott_hal Halindex="1" Hazon="1" VerAzon="1">
            <THal>Csuka</THal>
            <Kg>5</Kg>
            <ido>14:00</ido>
        </Kifogott_hal>
        <Kifogott_hal Halindex="2" Hazon="2" VerAzon="2">
            <THal>Ponty</THal>
            <Kg>10</Kg>
            <ido>15:00</ido>
        </Kifogott_hal>
        <Kifogott_hal Halindex="3" Hazon="3" VerAzon="3">
            <THal>Amur</THal>
            <Kg>8</Kg>
            <ido>17:00</ido>
        </Kifogott_hal>
    </Kifogott_Halak>
    <Ellenorzesek>
        <Ellenorzes VBiroId="1" VersenyzoId="2">
            <Mikor>17:55</Mikor>
        </Ellenorzes>
        <Ellenorzes VBiroId="1" VersenyzoId="1">
            <Mikor>17:50</Mikor>
        </Ellenorzes>
        <Ellenorzes VBiroId="3" VersenyzoId="3">
            <Mikor>17:45</Mikor>
        </Ellenorzes>
        <Ellenorzes VBiroId="3" VersenyzoId="2">
            <Mikor>17:40</Mikor>
        </Ellenorzes>
        <Ellenorzes VBiroId="2" VersenyzoId="1">
            <Mikor>17:35</Mikor>
        </Ellenorzes>
    </Ellenorzesek>
    <Dijak>
        <Dij Dazon="1">
            <DNev>Legtobb_Hal</DNev>
            <Erteke>5000</Erteke>
            <At_adasi_idopont>18:00</At_adasi_idopont>
        </Dij>
        <Dij Dazon="2">
            <DNev>Legnagyobb_Hal</DNev>
            <Erteke>5000</Erteke>
            <At_adasi_idopont>18:30</At_adasi_idopont>
        </Dij>
        <Dij Dazon="3">
            <DNev>Gyoztes</DNev>
            <Erteke>20000</Erteke>
            <At_adasi_idopont>19:00</At_adasi_idopont>
        </Dij>
    </Dijak>
    <Helyszinek>
        <Helyszin SzektorAzon="1">
            <Helyszin_tipusa>Alacsony_part</Helyszin_tipusa>
            <Meret>2033</Meret>
            <Szektor>A</Szektor>
        </Helyszin>
        <Helyszin SzektorAzon="2">
            <Helyszin_tipusa>Magas_part</Helyszin_tipusa>
            <Meret>25</Meret>
            <Szektor>B</Szektor>
        </Helyszin>
        <Helyszin SzektorAzon="3">
            <Helyszin_tipusa>Alacsony_part</Helyszin_tipusa>
            <Meret>30</Meret>
            <Szektor>C</Szektor>
        </Helyszin>
    </Helyszinek>
    <Hal_Tipusok>
        <Hal_Tipus index="1">
            <Ragadozo>igen</Ragadozo>
            <Tipusa>VedettHal</Tipusa>
            <Oshonos>nem</Oshonos>
        </Hal_Tipus>
        <Hal_Tipus index="2">
            <Ragadozo>nem</Ragadozo>
            <Tipusa>VedettHal</Tipusa>
            <Oshonos>igen</Oshonos>
        </Hal_Tipus>
        <Hal_Tipus index="3">
            <Ragadozo>igen</Ragadozo>
            <Tipusa>NemVedettHal</Tipusa>
            <Oshonos>igen</Oshonos>
        </Hal_Tipus>
    </Hal_Tipusok>
</root>
